import {IProductsObject} from '../interfaces/products/products.interfaces'

const productsObject: IProductsObject = {
  english: {
    A: ["apple", "apricot"],
    B: [],
    C: [
      "carrot",
      "cabbage",
      "coconut",
      "cucumber",
      "celery",
      "couliflower",
      "courgette",
      "capers",
      "celeriac",
    ],
    D: [],
    E: [],
    F: [],
    G: [],
    H: [],
    I: [],
    J: [],
    K: [],
    L: ["lettuce"],
    M: [],
    N: [],
    O: [],
    P: ["pineapple"],
    Q: [],
    R: ["raddish"],
    S: [],
    T: ["tomato"],
    U: [],
    V: [],
    W: [],
    X: [],
    Y: [],
    Z: [],
  },
  polish: {
    A: ["apple", "apricot"],
    B: [],
    C: [
      "carrot",
      "cabbage",
      "coconut",
      "cucumber",
      "celery",
      "couliflower",
      "courgette",
      "capers",
      "celeriac",
    ],
    D: [],
    E: [],
    F: [],
    G: [],
    H: [],
    I: [],
    J: [],
    K: [],
    L: ["lettuce"],
    M: [],
    N: [],
    O: [],
    P: ["pineapple"],
    Q: [],
    R: ["raddish"],
    S: [],
    T: ["tomato"],
    U: [],
    V: [],
    W: [],
    X: [],
    Y: [],
    Z: [],
  }
};

const products: string[] = [
  "apple",
  "apricot",
  "pineapple",
  "tomato",
  "carrot",
  "cabbage",
  "coconut",
  "cucumber",
  "celery",
  "couliflower",
  "courgette",
  "lettuce",
  "raddish",
  "capers",
  "celeriac",
];

export { products, productsObject };
